### ISSUE TITLE
both Galaxy. ga output and xml should have the  name. 

### ISSUE THREAD

**Issue by happykhan** [phac-nml/irida-wf-ga2xml#5]
running as : 

`java -jar irida-wf-ga2xml-1.0.0-SNAPSHOT-standalone.jar -i AssemblyAnnotation.json  -W 0.5 -t ASSEMBLY_ANNOTATION -n AssemblyAnnotation -o zz`

In the output from xml: 

`<name>AssemblyAnnotation</name>`

In the output from .ga file: 

`"name": "AssemblyAnnotation_master",` (which was the original name in the original galaxy ga)

Is there a reason why the .ga file doesn't also set its name to the -n parameter? 

I believe it should honour the -n flag.

**Comment by apetkau** [comment]
The main reason was that there was no need to modify the .ga file since the "name" value in the Galaxy workflow isn't used by IRIDA.  But, keeping the "name" consistent in the .ga file and the .xml file would make things a bit easier, so I'll look into doing this.
